### ISSUE TITLE
Q: How to specify complex initializations?

### ISSUE THREAD

**Issue by torotil** [ets-labs/python-dependency-injector#338]
A generic form of specifying how to instantiate a class is to specify args/kwargs for the constructor and then a sequence of method invocations an example would be:

```yaml
example_service:
  class: my_module.Example
  args: [1, 2, @service3]
  kwargs:
    foo: @foo_service
  calls:
  - method: setBar
    args:
    - @bar_service
```

How would this translate for this package?

I did consult the docs (especially the section about providers) but I wasn’t able to find something like this.
